# Generated by Django 3.1 on 2020-08-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200825_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='overall_progress',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
