# Generated by Django 3.1 on 2020-08-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200825_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='percent_complete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
