# Generated by Django 3.1 on 2020-08-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_percent_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='percent_complete',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
