# Generated by Django 3.1 on 2020-08-26 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20200826_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='profile',
        ),
        migrations.AddField(
            model_name='semester',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='auth.user'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
