# Generated by Django 3.1 on 2020-08-27 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200826_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlannedCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('term', models.CharField(max_length=200)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('code', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_courses', to='api.category')),
            ],
        ),
        migrations.AlterField(
            model_name='semester',
            name='courses',
            field=models.ManyToManyField(related_name='semesters', to='api.PlannedCourse'),
        ),
    ]
