# Generated by Django 3.1 on 2020-08-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200827_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
    ]
