# Generated by Django 3.1 on 2020-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200827_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits_towards',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
