# Generated by Django 3.1 on 2020-08-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200827_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credits_towards',
            new_name='credits',
        ),
    ]
