# Generated by Django 3.1 on 2020-08-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200827_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='category',
            name='percent_complete',
        ),
        migrations.RemoveField(
            model_name='program',
            name='met_groups',
        ),
        migrations.RemoveField(
            model_name='program',
            name='overall_progress',
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='program',
            name='number_of_requirements',
            field=models.IntegerField(default=0),
        ),
    ]
