# Generated by Django 3.1 on 2020-08-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200827_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits_required',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
