# Generated by Django 3.1 on 2020-08-28 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200828_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits_required',
            field=models.IntegerField(default=0),
        ),
    ]
